"""Seed data: streaming services, genres, and movies/shows.

Movie posters and backdrops use TMDB-public CDN style image URLs (image.tmdb.org)
which serve real, well-known title artwork. These are public assets used widely.
"""

_TMDB_IMG = "https://image.tmdb.org/t/p/w92"

# STREAMING_SERVICES `price_monthly` values mirror the CHEAPEST STANDARD
# (non-promo, non-addon) paid plan for each service in backend/pricing.py, so
# legacy callers that read price_monthly stay consistent with the plan table.
# Free / licence-required services are 0.  See backend/pricing.py for the full
# per-service plan breakdown (region GB, currency GBP).
STREAMING_SERVICES = [
    {"id": "netflix",        "name": "Netflix",      "price_monthly":  5.99, "logo_color": "#E50914", "affiliate_url": "https://www.netflix.com/",              "logo_path": f"{_TMDB_IMG}/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg"},
    {"id": "disney_plus",    "name": "Disney+",      "price_monthly":  5.99, "logo_color": "#0E47A1", "affiliate_url": "https://www.disneyplus.com/",           "logo_path": f"{_TMDB_IMG}/97yvRBw1GzX7fXprcF80er19ot.jpg"},
    {"id": "hbo_max",        "name": "Max",          "price_monthly":  9.99, "logo_color": "#002BE7", "affiliate_url": "https://www.max.com/",                  "logo_path": f"{_TMDB_IMG}/jbe4gVSfRlbPTdESXhEKpornsfu.jpg"},
    {"id": "prime_video",    "name": "Prime Video",  "price_monthly":  8.99, "logo_color": "#00A8E1", "affiliate_url": "https://www.primevideo.com/",           "logo_path": f"{_TMDB_IMG}/pvske1MyAoymrs5bguRfVqYiM9a.jpg"},
    {"id": "apple_tv",       "name": "Apple TV+",    "price_monthly":  9.99, "logo_color": "#A6A6A6", "affiliate_url": "https://tv.apple.com/",                 "logo_path": f"{_TMDB_IMG}/mcbz1LgtErU9p4UdbZ0rG6RTWHX.jpg"},
    {"id": "paramount",      "name": "Paramount+",   "price_monthly":  4.99, "logo_color": "#0064FF", "affiliate_url": "https://www.paramountplus.com/",        "logo_path": f"{_TMDB_IMG}/h5DcR0J2EESLitnhR8xLG1QymTE.jpg"},
    {"id": "itvx",           "name": "ITVX",         "price_monthly":  5.99, "logo_color": "#DEEB52", "affiliate_url": "https://www.itv.com/watch",             "logo_path": ""},
    {"id": "now_tv",         "name": "NOW",          "price_monthly":  7.99, "logo_color": "#00818A", "affiliate_url": "https://www.nowtv.com/",                "logo_path": ""},
    {"id": "channel_4",      "name": "Channel 4",    "price_monthly":  3.99, "logo_color": "#AA00FF", "affiliate_url": "https://www.channel4.com/",             "logo_path": ""},
    {"id": "discovery_plus", "name": "discovery+",   "price_monthly":  3.99, "logo_color": "#0077FF", "affiliate_url": "https://www.discoveryplus.com/gb/",     "logo_path": ""},
    {"id": "bbc_iplayer",    "name": "BBC iPlayer",  "price_monthly":  0.0,  "logo_color": "#FF4E98", "affiliate_url": "https://www.bbc.co.uk/iplayer",         "logo_path": ""},
    {"id": "mubi",           "name": "MUBI",         "price_monthly": 11.99, "logo_color": "#000000", "affiliate_url": "https://mubi.com/",                     "logo_path": ""},
    # ── US-only services — kept for backward compatibility with existing data,
    #    but NOT selectable in the UK market (active=False, us_only=True). ────────
    {"id": "hulu",           "name": "Hulu",         "price_monthly":  7.99, "logo_color": "#1CE783", "affiliate_url": "https://www.hulu.com/",                 "logo_path": f"{_TMDB_IMG}/bxBlRPEPpMVDc4jMhSrTf2339DW.jpg", "active": False, "us_only": True},
    {"id": "peacock",        "name": "Peacock",      "price_monthly":  7.99, "logo_color": "#FA6400", "affiliate_url": "https://www.peacocktv.com/",            "logo_path": f"{_TMDB_IMG}/2aGrp1xw3qhwCYvNGAJZPdjfeeX.jpg", "active": False, "us_only": True},
]

GENRES = [
    "Action", "Adventure", "Animation", "Comedy", "Crime", "Documentary",
    "Drama", "Fantasy", "Horror", "Mystery", "Romance", "Sci-Fi",
    "Thriller", "Western",
]

# id, title, year, rating (TMDB-style 0-10), vote_count, popularity, runtime (min),
# genres, type, overview, poster_url, backdrop_url, trailer_youtube_id, available_on, tags
SEED_MOVIES = [
    # ── Existing 24 (with added vote_count / popularity / tags) ─────────────
    {
        "id": "m_oppenheimer", "title": "Oppenheimer", "year": 2023, "rating": 8.4,
        "vote_count": 320000, "popularity": 145.0, "runtime": 180,
        "genres": ["Drama", "Thriller"], "type": "movie",
        "overview": "The story of J. Robert Oppenheimer's role in the development of the atomic bomb.",
        "poster_url": "https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
        "trailer_youtube_id": "uYPbbksJxIg",
        "available_on": ["peacock", "prime_video"], "tags": [],
    },
    {
        "id": "m_dune2", "title": "Dune: Part Two", "year": 2024, "rating": 8.3,
        "vote_count": 280000, "popularity": 132.0, "runtime": 166,
        "genres": ["Sci-Fi", "Adventure"], "type": "movie",
        "overview": "Paul Atreides unites with the Fremen to take revenge against the conspirators who destroyed his family.",
        "poster_url": "https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
        "trailer_youtube_id": "Way9Dexny3w",
        "available_on": ["hbo_max"], "tags": [],
    },
    {
        "id": "m_succession", "title": "Succession", "year": 2018, "rating": 8.9,
        "vote_count": 185000, "popularity": 98.0, "runtime": 60,
        "genres": ["Drama", "Comedy"], "type": "tv",
        "overview": "Follows the lives of the Roy family as they contemplate their future once their patriarch begins to step back from the media empire.",
        "poster_url": "https://image.tmdb.org/t/p/w780/7HW47XbkNQ5fiwQFYGWdw9gs144.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/AeKCJEcmpJzNGuhPhrmeLaaO0F4.jpg",
        "trailer_youtube_id": "OzYxJV_rmE8",
        "available_on": ["hbo_max"], "tags": [],
    },
    {
        "id": "m_severance", "title": "Severance", "year": 2022, "rating": 8.7,
        "vote_count": 210000, "popularity": 110.0, "runtime": 55,
        "genres": ["Sci-Fi", "Mystery", "Thriller"], "type": "tv",
        "overview": "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.",
        "poster_url": "https://image.tmdb.org/t/p/w780/lFf6LLrQjYldcZItzOkGmMMigP7.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/wnjjkqFVK9o4Cg5GVeXa5jK4Bvn.jpg",
        "trailer_youtube_id": "xEQP4VVuyrY",
        "available_on": ["apple_tv"], "tags": [],
    },
    {
        "id": "m_thebear", "title": "The Bear", "year": 2022, "rating": 8.5,
        "vote_count": 195000, "popularity": 95.0, "runtime": 30,
        "genres": ["Drama", "Comedy"], "type": "tv",
        "overview": "A young chef from the fine-dining world returns to Chicago to run his late brother's sandwich shop.",
        "poster_url": "https://image.tmdb.org/t/p/w780/zPyHo2rfnLIkXbkVdHFOXoZALDJ.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/yZNfO3LDDtAvKBpYTVRDSrPnclI.jpg",
        "trailer_youtube_id": "Ux1iX5RKfUE",
        "available_on": ["hulu", "disney_plus"], "tags": [],
    },
    {
        "id": "m_killersflowermoon", "title": "Killers of the Flower Moon", "year": 2023, "rating": 7.6,
        "vote_count": 145000, "popularity": 68.0, "runtime": 206,
        "genres": ["Crime", "Drama", "Western"], "type": "movie",
        "overview": "Members of the Osage tribe in the United States are murdered under mysterious circumstances in the 1920s.",
        "poster_url": "https://image.tmdb.org/t/p/w780/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/270RtIhkDqf1eyMUq3wkz3iMCAh.jpg",
        "trailer_youtube_id": "EP34Yoxs3FQ",
        "available_on": ["apple_tv", "prime_video"], "tags": [],
    },
    {
        "id": "m_strangerthings", "title": "Stranger Things", "year": 2016, "rating": 8.6,
        "vote_count": 310000, "popularity": 120.0, "runtime": 50,
        "genres": ["Sci-Fi", "Horror", "Drama"], "type": "tv",
        "overview": "When a young boy vanishes, a small town uncovers a mystery involving secret experiments and supernatural forces.",
        "poster_url": "https://image.tmdb.org/t/p/w780/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
        "trailer_youtube_id": "b9EkMc79ZSU",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_thecrown", "title": "The Crown", "year": 2016, "rating": 8.6,
        "vote_count": 175000, "popularity": 85.0, "runtime": 60,
        "genres": ["Drama"], "type": "tv",
        "overview": "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the 20th century.",
        "poster_url": "https://image.tmdb.org/t/p/w780/1M876KPjulVwppEpldhdc8V4o68.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/nGsv7uqfkSlTkW8WMnPVoEKyDrJ.jpg",
        "trailer_youtube_id": "JWtnJjn6ng0",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_andor", "title": "Andor", "year": 2022, "rating": 8.4,
        "vote_count": 155000, "popularity": 75.0, "runtime": 50,
        "genres": ["Sci-Fi", "Action", "Adventure"], "type": "tv",
        "overview": "Cassian Andor's journey to discover the difference he can make in the Star Wars galaxy on a mission of revenge.",
        "poster_url": "https://image.tmdb.org/t/p/w780/loFmBXAXTaPpeJYrJMnk4F8e2hG.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/cbFFQk5dmUHukyEYlCay82SDPDV.jpg",
        "trailer_youtube_id": "Vk6FmzPXZoQ",
        "available_on": ["disney_plus"], "tags": [],
    },
    {
        "id": "m_lastofus", "title": "The Last of Us", "year": 2023, "rating": 8.7,
        "vote_count": 240000, "popularity": 112.0, "runtime": 60,
        "genres": ["Drama", "Action", "Horror"], "type": "tv",
        "overview": "Twenty years after modern civilization has been destroyed, Joel must smuggle Ellie out of an oppressive quarantine zone.",
        "poster_url": "https://image.tmdb.org/t/p/w780/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
        "trailer_youtube_id": "uLtkt8BonwM",
        "available_on": ["hbo_max"], "tags": [],
    },
    {
        "id": "m_poorthings", "title": "Poor Things", "year": 2023, "rating": 7.9,
        "vote_count": 132000, "popularity": 62.0, "runtime": 141,
        "genres": ["Comedy", "Drama", "Sci-Fi"], "type": "movie",
        "overview": "The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant scientist Dr. Godwin Baxter.",
        "poster_url": "https://image.tmdb.org/t/p/w780/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
        "trailer_youtube_id": "RR6N5KYDdTk",
        "available_on": ["hulu", "disney_plus"], "tags": [],
    },
    {
        "id": "m_pastlives", "title": "Past Lives", "year": 2023, "rating": 7.9,
        "vote_count": 98000, "popularity": 48.0, "runtime": 105,
        "genres": ["Drama", "Romance"], "type": "movie",
        "overview": "Two childhood friends are reunited 20 years later to confront notions of love and destiny.",
        "poster_url": "https://image.tmdb.org/t/p/w780/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/n4GJFGzsc7NinI1VeGDXIcQjtU2.jpg",
        "trailer_youtube_id": "kA37rOOY3yU",
        "available_on": ["paramount", "prime_video"], "tags": [],
    },
    {
        "id": "m_tedlasso", "title": "Ted Lasso", "year": 2020, "rating": 8.6,
        "vote_count": 165000, "popularity": 78.0, "runtime": 30,
        "genres": ["Comedy", "Drama"], "type": "tv",
        "overview": "American football coach Ted Lasso heads to London to manage AFC Richmond, a struggling English Premier League soccer team.",
        "poster_url": "https://image.tmdb.org/t/p/w780/5fhZdwP1DVJ0FyVHvfO0XfLjsQk.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
        "trailer_youtube_id": "3u7EIiohs6U",
        "available_on": ["apple_tv"], "tags": [],
    },
    {
        "id": "m_barbie", "title": "Barbie", "year": 2023, "rating": 7.2,
        "vote_count": 290000, "popularity": 108.0, "runtime": 114,
        "genres": ["Comedy", "Adventure", "Fantasy"], "type": "movie",
        "overview": "Barbie suffers a crisis that leads her to question her world and her existence.",
        "poster_url": "https://image.tmdb.org/t/p/w780/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/nHf61UzkfFno5X1ofIhugCPus5n.jpg",
        "trailer_youtube_id": "pBk4NYhWNMM",
        "available_on": ["hbo_max"], "tags": [],
    },
    {
        "id": "m_breakingbad", "title": "Breaking Bad", "year": 2008, "rating": 8.9,
        "vote_count": 350000, "popularity": 135.0, "runtime": 49,
        "genres": ["Drama", "Crime", "Thriller"], "type": "tv",
        "overview": "A high school chemistry teacher diagnosed with terminal cancer turns to manufacturing meth to secure his family's future.",
        "poster_url": "https://image.tmdb.org/t/p/w780/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
        "trailer_youtube_id": "HhesaQXLuRY",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_themandalorian", "title": "The Mandalorian", "year": 2019, "rating": 8.4,
        "vote_count": 220000, "popularity": 90.0, "runtime": 40,
        "genres": ["Sci-Fi", "Action", "Adventure"], "type": "tv",
        "overview": "A lone gunfighter makes his way through the outer reaches of the galaxy, far from the authority of the New Republic.",
        "poster_url": "https://image.tmdb.org/t/p/w780/sWgBv7LV2PRoQkxwlibdGXKz1S.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/9ijMGlJKqcslswWUzTEwScm82Gs.jpg",
        "trailer_youtube_id": "aOC8E8z_ifw",
        "available_on": ["disney_plus"], "tags": [],
    },
    {
        "id": "m_johnwick4", "title": "John Wick: Chapter 4", "year": 2023, "rating": 7.7,
        "vote_count": 198000, "popularity": 88.0, "runtime": 169,
        "genres": ["Action", "Thriller", "Crime"], "type": "movie",
        "overview": "John Wick uncovers a path to defeating The High Table, but before he can earn his freedom, he must face off against a new enemy.",
        "poster_url": "https://image.tmdb.org/t/p/w780/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
        "trailer_youtube_id": "qEVUtrk8_B4",
        "available_on": ["peacock", "prime_video"], "tags": [],
    },
    {
        "id": "m_whitelotus", "title": "The White Lotus", "year": 2021, "rating": 7.9,
        "vote_count": 168000, "popularity": 82.0, "runtime": 60,
        "genres": ["Drama", "Comedy", "Mystery"], "type": "tv",
        "overview": "The exploits of various guests and employees at a tropical resort over the span of a week.",
        "poster_url": "https://image.tmdb.org/t/p/w780/gP7OBvAmuW0gWCiZv7aw0vBXgOh.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/bJP6bOfdIwskaW4PwCw9NPL62qY.jpg",
        "trailer_youtube_id": "TEGEcA3Ar50",
        "available_on": ["hbo_max"], "tags": [],
    },
    {
        "id": "m_spiderverse", "title": "Spider-Man: Across the Spider-Verse", "year": 2023, "rating": 8.4,
        "vote_count": 240000, "popularity": 105.0, "runtime": 140,
        "genres": ["Animation", "Action", "Adventure"], "type": "movie",
        "overview": "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
        "poster_url": "https://image.tmdb.org/t/p/w780/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/4HodYYKEIsGOdinkGi2Ucwxn3Vp.jpg",
        "trailer_youtube_id": "cqGjhVJWtEg",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_house_dragon", "title": "House of the Dragon", "year": 2022, "rating": 8.4,
        "vote_count": 215000, "popularity": 100.0, "runtime": 60,
        "genres": ["Drama", "Fantasy", "Action"], "type": "tv",
        "overview": "The Targaryen civil war, known as the Dance of the Dragons, set 200 years before the events of Game of Thrones.",
        "poster_url": "https://image.tmdb.org/t/p/w780/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
        "trailer_youtube_id": "DotnHcOpCB8",
        "available_on": ["hbo_max"], "tags": [],
    },
    {
        "id": "m_anatomyfall", "title": "Anatomy of a Fall", "year": 2023, "rating": 7.7,
        "vote_count": 112000, "popularity": 52.0, "runtime": 152,
        "genres": ["Drama", "Crime", "Mystery"], "type": "movie",
        "overview": "A woman is suspected of murder after her husband's death; their half-blind son faces a moral dilemma as the main witness.",
        "poster_url": "https://image.tmdb.org/t/p/w780/kQs6keheMwCxJxrzV83VUwFtHkB.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/27mpiyhqAN0Pz9hbf85t1EtvnvK.jpg",
        "trailer_youtube_id": "lE9VRCi4yXQ",
        "available_on": ["hulu", "prime_video"], "tags": [],
    },
    {
        "id": "m_friends", "title": "Friends", "year": 1994, "rating": 8.4,
        "vote_count": 295000, "popularity": 115.0, "runtime": 22,
        "genres": ["Comedy", "Romance"], "type": "tv",
        "overview": "Six young people navigate life and love in Manhattan in this iconic sitcom.",
        "poster_url": "https://image.tmdb.org/t/p/w780/f496cm9enuEsZkSPzCwnTESEK5s.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/l0qVZIpXtIo7km9u5Yqh0nKPOr5.jpg",
        "trailer_youtube_id": "cBR-XLLEVew",
        "available_on": ["hbo_max"], "tags": [],
    },
    {
        "id": "m_loki", "title": "Loki", "year": 2021, "rating": 8.2,
        "vote_count": 185000, "popularity": 80.0, "runtime": 50,
        "genres": ["Sci-Fi", "Fantasy", "Action"], "type": "tv",
        "overview": "The mercurial villain Loki resumes his role as the God of Mischief in a new series that takes place after the events of Avengers: Endgame.",
        "poster_url": "https://image.tmdb.org/t/p/w780/voHUmluYmKyleFkTu3lOXQG702u.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/g0rCwu0t4hL4nwAerFqSXlZdBrE.jpg",
        "trailer_youtube_id": "nW948Va-l10",
        "available_on": ["disney_plus"], "tags": [],
    },
    {
        "id": "m_tar", "title": "Tár", "year": 2022, "rating": 7.4,
        "vote_count": 88000, "popularity": 42.0, "runtime": 158,
        "genres": ["Drama"], "type": "movie",
        "overview": "Set in the international world of classical music, the film centers on Lydia Tár, a renowned conductor.",
        "poster_url": "https://image.tmdb.org/t/p/w780/n13UJrZNEY4u0PuvjAo5pjDe0OL.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/aDFiTqQMV5VyiQ3OOLGu9XAmfPv.jpg",
        "trailer_youtube_id": "aZkBaywpAEQ",
        "available_on": ["peacock"], "tags": [],
    },

    # ── NEW: Netflix ──────────────────────────────────────────────────────────
    {
        "id": "m_squidgame", "title": "Squid Game", "year": 2021, "rating": 7.9,
        "vote_count": 315000, "popularity": 150.0, "runtime": 55,
        "genres": ["Drama", "Thriller", "Action"], "type": "tv",
        "overview": "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a brutal survival competition awaits with deadly consequences.",
        "poster_url": "https://image.tmdb.org/t/p/w780/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/qw3J9cNeLioOLoR68WX7z79aCdK.jpg",
        "trailer_youtube_id": "oqxAJKy0ii4",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_ozark", "title": "Ozark", "year": 2017, "rating": 8.4,
        "vote_count": 195000, "popularity": 88.0, "runtime": 60,
        "genres": ["Drama", "Crime", "Thriller"], "type": "tv",
        "overview": "A financial advisor drags his family from Chicago to the Missouri Ozarks after a money-laundering scheme goes wrong.",
        "poster_url": "https://image.tmdb.org/t/p/w780/pfd0D3RZuuMSJ9JEiCRVUQ8bFP0.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/7yllNSClLiCAE0ZOyb9oPBuHXhk.jpg",
        "trailer_youtube_id": "5hAYNITGpiM",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_dark", "title": "Dark", "year": 2017, "rating": 8.7,
        "vote_count": 152000, "popularity": 74.0, "runtime": 60,
        "genres": ["Sci-Fi", "Mystery", "Drama"], "type": "tv",
        "overview": "A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four family trees.",
        "poster_url": "https://image.tmdb.org/t/p/w780/apbrbWs5M9DKAN5BroIQLUAkUXo.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/nMRwjAKb2BCHKP9XGHl8xzKjzEQ.jpg",
        "trailer_youtube_id": "ESGAk7DoVJE",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_wednesday", "title": "Wednesday", "year": 2022, "rating": 8.1,
        "vote_count": 185000, "popularity": 92.0, "runtime": 50,
        "genres": ["Horror", "Comedy", "Mystery"], "type": "tv",
        "overview": "Wednesday Addams is sent to Nevermore Academy, a school for outcasts, where she attempts to master her psychic ability while uncovering a monstrous killing spree.",
        "poster_url": "https://image.tmdb.org/t/p/w780/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
        "trailer_youtube_id": "Di310WS9zLQ",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_thewitcher", "title": "The Witcher", "year": 2019, "rating": 8.0,
        "vote_count": 198000, "popularity": 86.0, "runtime": 60,
        "genres": ["Fantasy", "Action", "Drama"], "type": "tv",
        "overview": "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
        "poster_url": "https://image.tmdb.org/t/p/w780/7vjaCdMw15FEbXyLQTVa04URsPm.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg",
        "trailer_youtube_id": "ndl7APmPxso",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_peakyblin", "title": "Peaky Blinders", "year": 2013, "rating": 8.8,
        "vote_count": 245000, "popularity": 102.0, "runtime": 60,
        "genres": ["Crime", "Drama"], "type": "tv",
        "overview": "A gangster family epic set in Birmingham, England after the First World War, centering on the Peaky Blinders crime gang.",
        "poster_url": "https://image.tmdb.org/t/p/w780/vUUqzWa2LnHIVqkaKVgCharJmKi.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/wiE9doxiLwq3WierbiH5Ltzn7sh.jpg",
        "trailer_youtube_id": "oVzVdvGIC7U",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_mindhunter", "title": "Mindhunter", "year": 2017, "rating": 8.6,
        "vote_count": 148000, "popularity": 70.0, "runtime": 60,
        "genres": ["Crime", "Drama", "Thriller"], "type": "tv",
        "overview": "In the late 1970s two FBI agents expand criminal science by delving into the psychology of murder and getting inside the minds of serial killers.",
        "poster_url": "https://image.tmdb.org/t/p/w780/afGi4EDVG5DAHKvhKAHpSI3BQHD.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/r74iIKFMJvCOMFnOSfYHYOhfHIU.jpg",
        "trailer_youtube_id": "gMuXGV7Pqsw",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_knivesout", "title": "Knives Out", "year": 2019, "rating": 7.9,
        "vote_count": 365000, "popularity": 118.0, "runtime": 130,
        "genres": ["Crime", "Mystery", "Comedy"], "type": "movie",
        "overview": "When a renowned crime novelist is found dead at his estate, a detective and a troupe of dysfunctional family members are suspected.",
        "poster_url": "https://image.tmdb.org/t/p/w780/pThyQovXQrws2hmLinLSVoygN5i.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/4HodYYKEIsGOdinkGi2Ucwxn3Vp.jpg",
        "trailer_youtube_id": "qGqiHJTsRkQ",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_glassonion", "title": "Glass Onion: A Knives Out Mystery", "year": 2022, "rating": 7.2,
        "vote_count": 285000, "popularity": 95.0, "runtime": 139,
        "genres": ["Crime", "Mystery", "Comedy"], "type": "movie",
        "overview": "Detective Benoit Blanc travels to Greece for his latest case: unmasking the killer at a lavish event hosted by a tech billionaire.",
        "poster_url": "https://image.tmdb.org/t/p/w780/vClmWWYNK4jdnbMZh44d6VQvJKb.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/j1neiDMBiaDXCWtWBnUJvhZuTYI.jpg",
        "trailer_youtube_id": "5SUMoMRdHW8",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_marriagestory", "title": "Marriage Story", "year": 2019, "rating": 7.9,
        "vote_count": 178000, "popularity": 72.0, "runtime": 137,
        "genres": ["Drama", "Romance"], "type": "movie",
        "overview": "A stage director and his actress wife struggle through a grueling, coast-to-coast divorce that pushes them to their personal and creative extremes.",
        "poster_url": "https://image.tmdb.org/t/p/w780/scZlQQYnDVlnpxFTxaIv2G0BWnL.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/39wRDFl8j9o4OHHPjFhbMr5RTGI.jpg",
        "trailer_youtube_id": "BHsG6GE83zk",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_irishman", "title": "The Irishman", "year": 2019, "rating": 7.8,
        "vote_count": 195000, "popularity": 76.0, "runtime": 209,
        "genres": ["Crime", "Drama"], "type": "movie",
        "overview": "An aging hitman recalls his time with the mob and his involvement in the murder of Jimmy Hoffa.",
        "poster_url": "https://image.tmdb.org/t/p/w780/oePpB4g9enwpFsGHue29p5DKCoM.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/qEFqFKTXerCUnLHNpFQ8BNKN3aG.jpg",
        "trailer_youtube_id": "WHXxVmeGQUc",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_societysnow", "title": "Society of the Snow", "year": 2023, "rating": 7.7,
        "vote_count": 115000, "popularity": 55.0, "runtime": 144,
        "genres": ["Drama", "Thriller"], "type": "movie",
        "overview": "A Uruguayan rugby team's plane crashes in the Andes and the survivors are forced to resort to extreme measures to stay alive.",
        "poster_url": "https://image.tmdb.org/t/p/w780/2e858BQhJEL7O9bDr2gXMHiTzaS.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/rOmUuQhxnRMMTXbJnTcBsFzQ1PH.jpg",
        "trailer_youtube_id": "wX43CRNIjvM",
        "available_on": ["netflix"], "tags": [],
    },

    # ── NEW: HBO Max ──────────────────────────────────────────────────────────
    {
        "id": "m_chernobyl", "title": "Chernobyl", "year": 2019, "rating": 9.4,
        "vote_count": 285000, "popularity": 125.0, "runtime": 60,
        "genres": ["Drama", "Mystery", "Thriller"], "type": "tv",
        "overview": "In April 1986, an explosion at the Chernobyl nuclear power plant in the USSR becomes one of the world's worst man-made catastrophes.",
        "poster_url": "https://image.tmdb.org/t/p/w780/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
        "trailer_youtube_id": "s9APLXM9Ei8",
        "available_on": ["hbo_max"], "tags": [],
    },
    {
        "id": "m_truedetective", "title": "True Detective", "year": 2014, "rating": 8.9,
        "vote_count": 225000, "popularity": 96.0, "runtime": 55,
        "genres": ["Crime", "Drama", "Mystery"], "type": "tv",
        "overview": "An anthology series where a single-case investigation is told through multiple time periods and detectives with haunted pasts.",
        "poster_url": "https://image.tmdb.org/t/p/w780/y3ylBIzrpYBGGTD8eHJaYHHyxcE.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/bxVxZb1tqYyHCCqsHrdKDR1lnoI.jpg",
        "trailer_youtube_id": "WeNSNEwGqbQ",
        "available_on": ["hbo_max"], "tags": [],
    },
    {
        "id": "m_euphoria", "title": "Euphoria", "year": 2019, "rating": 8.4,
        "vote_count": 175000, "popularity": 88.0, "runtime": 55,
        "genres": ["Drama"], "type": "tv",
        "overview": "A group of high school students navigate love and friendships in a world of drugs, sex, trauma and social media.",
        "poster_url": "https://image.tmdb.org/t/p/w780/2QhLmXBbFPPKdBRGQdX4M0flmXm.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/jZIYaISP3GBDeATZPf5sVJOXazU.jpg",
        "trailer_youtube_id": "3i_FsqFRpXA",
        "available_on": ["hbo_max"], "tags": [],
    },
    {
        "id": "m_gameofthrones", "title": "Game of Thrones", "year": 2011, "rating": 9.2,
        "vote_count": 480000, "popularity": 175.0, "runtime": 60,
        "genres": ["Drama", "Fantasy", "Action"], "type": "tv",
        "overview": "Nine noble families fight for control of the mythical land of Westeros; meanwhile, a forgotten race returns to the world after being dormant for millennia.",
        "poster_url": "https://image.tmdb.org/t/p/w780/7WUHnWGx5OrhZMcTXZxRjxEpbZ.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
        "trailer_youtube_id": "bjqEWgDVPe0",
        "available_on": ["hbo_max"], "tags": [],
    },
    {
        "id": "m_westworld", "title": "Westworld", "year": 2016, "rating": 8.5,
        "vote_count": 198000, "popularity": 82.0, "runtime": 60,
        "genres": ["Sci-Fi", "Drama", "Mystery"], "type": "tv",
        "overview": "At the intersection of the near future and the reimagined past, humanoid robots called Hosts are key players in a vast theme-park adventure.",
        "poster_url": "https://image.tmdb.org/t/p/w780/8MfgyFHR7Hk9UmN7iCwBqalLFJm.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/n5GBeTAGG58bmEOaAOmP0LV5M7q.jpg",
        "trailer_youtube_id": "j4HFjMEOtD4",
        "available_on": ["hbo_max"], "tags": [],
    },
    {
        "id": "m_thewire", "title": "The Wire", "year": 2002, "rating": 9.3,
        "vote_count": 180000, "popularity": 78.0, "runtime": 60,
        "genres": ["Crime", "Drama", "Thriller"], "type": "tv",
        "overview": "The inner workings of law enforcement and criminality in Baltimore are explored through the stories of cops and drug dealers.",
        "poster_url": "https://image.tmdb.org/t/p/w780/4vFG5Ld8lTGPPVBScZjpXKEAlTK.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/xJ32pKLbD0gVL3bXXQQQ5JzjlxD.jpg",
        "trailer_youtube_id": "bEiU0NjcSak",
        "available_on": ["hbo_max"], "tags": [],
    },
    {
        "id": "m_thedarkknight", "title": "The Dark Knight", "year": 2008, "rating": 9.0,
        "vote_count": 580000, "popularity": 185.0, "runtime": 152,
        "genres": ["Action", "Crime", "Drama"], "type": "movie",
        "overview": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        "poster_url": "https://image.tmdb.org/t/p/w780/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/hkBaDkMWbLaf8B1lsWsNprs3hS.jpg",
        "trailer_youtube_id": "EXeTwQWrcwY",
        "available_on": ["hbo_max"], "tags": [],
    },
    {
        "id": "m_inception", "title": "Inception", "year": 2010, "rating": 8.8,
        "vote_count": 490000, "popularity": 160.0, "runtime": 148,
        "genres": ["Sci-Fi", "Action", "Thriller"], "type": "movie",
        "overview": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        "poster_url": "https://image.tmdb.org/t/p/w780/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
        "trailer_youtube_id": "YoHD9XEInc0",
        "available_on": ["hbo_max", "netflix"], "tags": [],
    },
    {
        "id": "m_bansheesofin", "title": "The Banshees of Inisherin", "year": 2022, "rating": 7.7,
        "vote_count": 145000, "popularity": 65.0, "runtime": 114,
        "genres": ["Drama", "Comedy"], "type": "movie",
        "overview": "On a remote Irish island, Pádraic is devastated when his lifelong best friend suddenly wants to end their friendship.",
        "poster_url": "https://image.tmdb.org/t/p/w780/4yFG5Ld8lTGPPVBScZjpXKEAlTK.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/gMIJMxTepuPuMh7Fz5GhNHaYB8V.jpg",
        "trailer_youtube_id": "uRu3zLOJN2c",
        "available_on": ["hbo_max"], "tags": [],
    },

    # ── NEW: Apple TV+ ────────────────────────────────────────────────────────
    {
        "id": "m_silo", "title": "Silo", "year": 2023, "rating": 7.9,
        "vote_count": 108000, "popularity": 62.0, "runtime": 55,
        "genres": ["Sci-Fi", "Drama", "Mystery"], "type": "tv",
        "overview": "In a ruined future, a community of thousands live in a giant underground silo to protect themselves from the toxic world outside.",
        "poster_url": "https://image.tmdb.org/t/p/w780/3hT0MEylOdCBqX1uiFOaEBfkdxE.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/rEYaJDMBtWvmx5Sxbj6BnHVMZ3k.jpg",
        "trailer_youtube_id": "2dWxPStyqY4",
        "available_on": ["apple_tv"], "tags": [],
    },
    {
        "id": "m_foundation", "title": "Foundation", "year": 2021, "rating": 7.3,
        "vote_count": 92000, "popularity": 55.0, "runtime": 60,
        "genres": ["Sci-Fi", "Drama", "Adventure"], "type": "tv",
        "overview": "A band of exiles embark on a monumental journey to preserve the knowledge of civilization and rebuild as a crumbling Galactic Empire threatens to plunge the universe into permanent darkness.",
        "poster_url": "https://image.tmdb.org/t/p/w780/vI5e6eLZLGQ1XBL7bS5KFJYJJoh.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/rK2snlxuJBGQlGMrGTRbaMPc0w0.jpg",
        "trailer_youtube_id": "qkuOVn3FvOI",
        "available_on": ["apple_tv"], "tags": [],
    },
    {
        "id": "m_slowhorses", "title": "Slow Horses", "year": 2022, "rating": 8.2,
        "vote_count": 85000, "popularity": 52.0, "runtime": 45,
        "genres": ["Thriller", "Crime", "Drama"], "type": "tv",
        "overview": "A dysfunctional group of British intelligence agents work for the MI5's dumping ground department called Slough House.",
        "poster_url": "https://image.tmdb.org/t/p/w780/xTzHunCSGmSf6B2l44qnEOaKR6X.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/h5kVYyH0gNh0UPMnTXDnm1aK0JJ.jpg",
        "trailer_youtube_id": "yNAVXIU0zdk",
        "available_on": ["apple_tv"], "tags": [],
    },
    {
        "id": "m_shrinking", "title": "Shrinking", "year": 2023, "rating": 8.1,
        "vote_count": 75000, "popularity": 48.0, "runtime": 30,
        "genres": ["Comedy", "Drama"], "type": "tv",
        "overview": "A grieving therapist starts breaking the rules and telling his patients exactly what he thinks, ignoring his training and ethics.",
        "poster_url": "https://image.tmdb.org/t/p/w780/ggKBMfVEAqM08JaHMWA94fWqkq5.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/y7c8ksYWpkQJiF9j0h0MCp7PjPG.jpg",
        "trailer_youtube_id": "8qPMUkEfOfE",
        "available_on": ["apple_tv"], "tags": [],
    },

    # ── NEW: Prime Video ─────────────────────────────────────────────────────
    {
        "id": "m_theboys", "title": "The Boys", "year": 2019, "rating": 8.7,
        "vote_count": 285000, "popularity": 138.0, "runtime": 60,
        "genres": ["Action", "Sci-Fi", "Comedy"], "type": "tv",
        "overview": "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers, while working to expose the corporation that manages them.",
        "poster_url": "https://image.tmdb.org/t/p/w780/mY7SeH4HFFxW1hiI6cWuwCRKptN.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/6msoLAifL62YD0fQHjdMRMWJOoM.jpg",
        "trailer_youtube_id": "M1bhOaLV4Oc",
        "available_on": ["prime_video"], "tags": [],
    },
    {
        "id": "m_reacher", "title": "Reacher", "year": 2022, "rating": 8.0,
        "vote_count": 145000, "popularity": 80.0, "runtime": 55,
        "genres": ["Action", "Crime", "Drama"], "type": "tv",
        "overview": "Decorated Military Police investigator Jack Reacher visits the small town of Margrave, Georgia — only to be immediately arrested for murder.",
        "poster_url": "https://image.tmdb.org/t/p/w780/sY7suMYAe5NVAY7M0xS2cZ4oFCE.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/wrVIjxFJrRjKNBiMzHaYn2cKFvG.jpg",
        "trailer_youtube_id": "tSXi1SHHIUI",
        "available_on": ["prime_video"], "tags": [],
    },
    {
        "id": "m_ringsofpower", "title": "The Rings of Power", "year": 2022, "rating": 7.0,
        "vote_count": 155000, "popularity": 72.0, "runtime": 60,
        "genres": ["Fantasy", "Adventure", "Drama"], "type": "tv",
        "overview": "Epic adventures set thousands of years before the events of J.R.R. Tolkien's 'The Hobbit' and 'The Lord of the Rings'.",
        "poster_url": "https://image.tmdb.org/t/p/w780/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/84ZMBBMHPtAQfmCnPlk5s2P9W6y.jpg",
        "trailer_youtube_id": "JrBHQmQCKx4",
        "available_on": ["prime_video"], "tags": [],
    },
    {
        "id": "m_fallout", "title": "Fallout", "year": 2024, "rating": 8.5,
        "vote_count": 138000, "popularity": 92.0, "runtime": 60,
        "genres": ["Sci-Fi", "Drama", "Comedy"], "type": "tv",
        "overview": "Based on the wildly popular video game series, Fallout is set in a world 200 years after nuclear armageddon where survivors now emerge from underground vaults.",
        "poster_url": "https://image.tmdb.org/t/p/w780/AnsSKvTNO2jls5hbpIcRFNVzDeZ.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/3bPcBTBZHhCCkHSVJVREYkLulhA.jpg",
        "trailer_youtube_id": "pM32EDMSbWg",
        "available_on": ["prime_video"], "tags": [],
    },
    {
        "id": "m_mrrobot", "title": "Mr. Robot", "year": 2015, "rating": 8.5,
        "vote_count": 165000, "popularity": 76.0, "runtime": 45,
        "genres": ["Drama", "Thriller", "Crime"], "type": "tv",
        "overview": "Elliot, a brilliant but highly unstable young cyber-security engineer and vigilante hacker, becomes recruited into the hacktivist group fsociety.",
        "poster_url": "https://image.tmdb.org/t/p/w780/oKIBhzZzDX07SoE2bOLhq2EE3mh.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/nVRyd8hlg0ZLxBn9RaI7mUMQLnz.jpg",
        "trailer_youtube_id": "xIBiJ_SzJTA",
        "available_on": ["prime_video"], "tags": [],
    },
    {
        "id": "m_parasite", "title": "Parasite", "year": 2019, "rating": 8.5,
        "vote_count": 350000, "popularity": 128.0, "runtime": 132,
        "genres": ["Drama", "Comedy", "Thriller"], "type": "movie",
        "overview": "All unemployed, Ki-taek and his family take a peculiar interest in the wealthy and elegant Park family, slipping into their lives one by one.",
        "poster_url": "https://image.tmdb.org/t/p/w780/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
        "trailer_youtube_id": "5xH0HfJHsaY",
        "available_on": ["hulu", "prime_video"], "tags": [],
    },
    {
        "id": "m_eeaao", "title": "Everything Everywhere All at Once", "year": 2022, "rating": 7.9,
        "vote_count": 320000, "popularity": 118.0, "runtime": 139,
        "genres": ["Sci-Fi", "Comedy", "Action"], "type": "movie",
        "overview": "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save the world by exploring other universes connecting with the lives she could have led.",
        "poster_url": "https://image.tmdb.org/t/p/w780/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/fePczpFBEA4ENXL87DHuBNBSCfr.jpg",
        "trailer_youtube_id": "wxN1T1uxQ2g",
        "available_on": ["prime_video", "hulu"], "tags": [],
    },
    {
        "id": "m_1917", "title": "1917", "year": 2019, "rating": 8.3,
        "vote_count": 295000, "popularity": 95.0, "runtime": 119,
        "genres": ["Drama", "Action", "Thriller"], "type": "movie",
        "overview": "Two young British soldiers during the First World War are given an impossible mission: deliver a message deep in enemy territory to stop 1,600 men from walking into a deadly ambush.",
        "poster_url": "https://image.tmdb.org/t/p/w780/iZf0KyrE25z1sage4SYQLv2nqpN.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
        "trailer_youtube_id": "YqNYrYUiMfg",
        "available_on": ["prime_video"], "tags": [],
    },
    {
        "id": "m_saltburn", "title": "Saltburn", "year": 2023, "rating": 7.1,
        "vote_count": 228000, "popularity": 85.0, "runtime": 127,
        "genres": ["Drama", "Thriller", "Mystery"], "type": "movie",
        "overview": "A student at Oxford University finds himself drawn into the world of a charming and aristocratic classmate who invites him to his eccentric family's sprawling estate.",
        "poster_url": "https://image.tmdb.org/t/p/w780/3poYBtL5ABUF5EFfS6AqBaELT2X.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/qjGom4B39ZVVRhDNNzH5gHgWHKT.jpg",
        "trailer_youtube_id": "6h0eHRJEQ48",
        "available_on": ["prime_video"], "tags": [],
    },

    # ── NEW: Hulu ─────────────────────────────────────────────────────────────
    {
        "id": "m_shogun", "title": "Shōgun", "year": 2024, "rating": 8.7,
        "vote_count": 135000, "popularity": 98.0, "runtime": 55,
        "genres": ["Drama", "Action"], "type": "tv",
        "overview": "In feudal Japan, a shipwrecked English sailor finds himself in the middle of a conflict between warlords fighting for control of the country.",
        "poster_url": "https://image.tmdb.org/t/p/w780/lJSk6BGX8kBfcTBRPE5f1kl9FiG.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/AiNiTZpJHwXkRFQpYPjGNVFdnFE.jpg",
        "trailer_youtube_id": "X7K6DZBV7KU",
        "available_on": ["hulu", "disney_plus"], "tags": [],
    },
    {
        "id": "m_hereditary", "title": "Hereditary", "year": 2018, "rating": 7.3,
        "vote_count": 198000, "popularity": 72.0, "runtime": 127,
        "genres": ["Horror", "Mystery", "Drama"], "type": "movie",
        "overview": "When the family matriarch passes away, a grieving family is haunted by tragic and disturbing occurrences as they try to outrun the sinister fate they have inherited.",
        "poster_url": "https://image.tmdb.org/t/p/w780/4QcDQntcmVuCFoT64jBFpJfzOdU.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/p8z2cJZXpOIhEL7yCiMYEMiimBt.jpg",
        "trailer_youtube_id": "V6wWKNij_1M",
        "available_on": ["hulu"], "tags": [],
    },
    {
        "id": "m_midsommar", "title": "Midsommar", "year": 2019, "rating": 7.1,
        "vote_count": 175000, "popularity": 68.0, "runtime": 148,
        "genres": ["Horror", "Mystery", "Drama"], "type": "movie",
        "overview": "A couple travels to Sweden to visit a rural hometown's fabled midsummer festival. What begins as an idyllic retreat quickly devolves into an increasingly disturbing and chaotic competition at the hands of a pagan cult.",
        "poster_url": "https://image.tmdb.org/t/p/w780/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/f0C4QaFJpQ4XcBGgGFTFMO8GQxA.jpg",
        "trailer_youtube_id": "1Vnghdsjmd0",
        "available_on": ["prime_video", "hulu"], "tags": [],
    },
    {
        "id": "m_getout", "title": "Get Out", "year": 2017, "rating": 7.7,
        "vote_count": 315000, "popularity": 95.0, "runtime": 104,
        "genres": ["Horror", "Mystery", "Thriller"], "type": "movie",
        "overview": "A young African-American visits his white girlfriend's parents for the weekend, where his unsettling discoveries lead to a dark truth.",
        "poster_url": "https://image.tmdb.org/t/p/w780/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/8tNhPseBMQyHmxFlDqKuakd2L2R.jpg",
        "trailer_youtube_id": "DzfpyUB60YY",
        "available_on": ["hulu", "prime_video"], "tags": [],
    },
    {
        "id": "m_realPain", "title": "A Real Pain", "year": 2024, "rating": 8.0,
        "vote_count": 88000, "popularity": 55.0, "runtime": 90,
        "genres": ["Drama", "Comedy"], "type": "movie",
        "overview": "Mismatched cousins David and Benji reunite for a trip through Poland to honour their beloved grandmother, but the adventure takes a turn when their old tensions come to a head.",
        "poster_url": "https://image.tmdb.org/t/p/w780/oBqKBNV1Zcf1A7r5TLq2jz0ldEK.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/qH0oNalV5uMBUhVJn80x7FNjW9k.jpg",
        "trailer_youtube_id": "BQMfFHjPStk",
        "available_on": ["hulu"], "tags": [],
    },

    # ── NEW: Peacock & Paramount+ ─────────────────────────────────────────────
    {
        "id": "m_holdovers", "title": "The Holdovers", "year": 2023, "rating": 8.0,
        "vote_count": 122000, "popularity": 60.0, "runtime": 133,
        "genres": ["Drama", "Comedy"], "type": "movie",
        "overview": "A curmudgeonly teacher at a New England prep school is forced to remain on campus during the Christmas break to babysit the students who can't return home.",
        "poster_url": "https://image.tmdb.org/t/p/w780/VHmCQdOPvBkPGEF6aBKU1v7R8o.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/GdFZ5VGDNB1qM7GAL2Nt3uJfyH.jpg",
        "trailer_youtube_id": "AhKMgBFQc8E",
        "available_on": ["peacock"], "tags": [],
    },
    {
        "id": "m_yellowstone", "title": "Yellowstone", "year": 2018, "rating": 8.7,
        "vote_count": 165000, "popularity": 90.0, "runtime": 60,
        "genres": ["Drama", "Western"], "type": "tv",
        "overview": "A large modern American ranch faces constant conflicts from competing interests in development, environmentalism, and Native American rights.",
        "poster_url": "https://image.tmdb.org/t/p/w780/kZFiDOwjNFObHuCAfN74VbpNjjH.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/aeMhDEy0lEMqFZmONiqRlBLRHJx.jpg",
        "trailer_youtube_id": "UKzNzS-SZFE",
        "available_on": ["peacock", "paramount"], "tags": [],
    },
    {
        "id": "m_interstellar", "title": "Interstellar", "year": 2014, "rating": 8.7,
        "vote_count": 490000, "popularity": 162.0, "runtime": 169,
        "genres": ["Sci-Fi", "Drama", "Adventure"], "type": "movie",
        "overview": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival as Earth's resources reach their limit.",
        "poster_url": "https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg",
        "trailer_youtube_id": "zSWdZVtXT7E",
        "available_on": ["netflix", "prime_video"], "tags": [],
    },
    {
        "id": "m_dune2021", "title": "Dune", "year": 2021, "rating": 8.0,
        "vote_count": 330000, "popularity": 122.0, "runtime": 155,
        "genres": ["Sci-Fi", "Adventure", "Drama"], "type": "movie",
        "overview": "Feature adaptation of Frank Herbert's science fiction novel, following Paul Atreides as his family accepts control of the desert planet Arrakis.",
        "poster_url": "https://image.tmdb.org/t/p/w780/d5NXSklpcvwN3u0sQFPuRMRjVnG.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/iopYFB1b6Bh7FWZh3onQhph1CZa.jpg",
        "trailer_youtube_id": "8g18jFHCLXk",
        "available_on": ["hbo_max"], "tags": [],
    },
    {
        "id": "m_allquiet", "title": "All Quiet on the Western Front", "year": 2022, "rating": 7.8,
        "vote_count": 178000, "popularity": 76.0, "runtime": 148,
        "genres": ["Drama", "Action"], "type": "movie",
        "overview": "A young German soldier's terrifying experiences and distress on the western front during World War I.",
        "poster_url": "https://image.tmdb.org/t/p/w780/hGGC9gKo7CFE3fW07RA587e5kol.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/k2twTjSddgLc1oFFHVibfxp2kQV.jpg",
        "trailer_youtube_id": "pBUQBhWwMRA",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_madmax", "title": "Mad Max: Fury Road", "year": 2015, "rating": 8.1,
        "vote_count": 420000, "popularity": 138.0, "runtime": 120,
        "genres": ["Action", "Adventure", "Sci-Fi"], "type": "movie",
        "overview": "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners, a psychotic worshipper, and a drifter named Max.",
        "poster_url": "https://image.tmdb.org/t/p/w780/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/phszHPFPGCcM9HNFNBqrV8P7FQT.jpg",
        "trailer_youtube_id": "hEJnMQG9ev8",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_conclave", "title": "Conclave", "year": 2024, "rating": 7.5,
        "vote_count": 98000, "popularity": 58.0, "runtime": 120,
        "genres": ["Drama", "Mystery", "Thriller"], "type": "movie",
        "overview": "After the Pope unexpectedly dies, the Dean of the College of Cardinals oversees the ancient ritual of selecting a new Pope — and stumbles onto a secret that could shake the very foundation of the Church.",
        "poster_url": "https://image.tmdb.org/t/p/w780/7FLmFHxzjNgGNGnrSYJMqCKODq3.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/theMCYOxB7IKBFU8VGlbHipfv04.jpg",
        "trailer_youtube_id": "5cPd-EENFKA",
        "available_on": ["prime_video"], "tags": [],
    },
    {
        "id": "m_americanfiction", "title": "American Fiction", "year": 2023, "rating": 7.6,
        "vote_count": 95000, "popularity": 52.0, "runtime": 117,
        "genres": ["Drama", "Comedy"], "type": "movie",
        "overview": "A frustrated novelist who's fed up with the establishment profiting from Black entertainment uses a pen name to write a book that propels him to the heart of the hypocrisy and madness he despises.",
        "poster_url": "https://image.tmdb.org/t/p/w780/rmDRVSX6ZAYm2FZxNVFCXsS1UuN.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/dtq9NiMFSQU1z6a2ZNMHQE4JpMY.jpg",
        "trailer_youtube_id": "AFlq2QDVxuM",
        "available_on": ["prime_video"], "tags": [],
    },
    {
        "id": "m_fargo", "title": "Fargo", "year": 2014, "rating": 8.9,
        "vote_count": 185000, "popularity": 82.0, "runtime": 50,
        "genres": ["Crime", "Drama", "Thriller"], "type": "tv",
        "overview": "An anthology series based on the Coen Brothers' film. A deeply humorous but extremely dark look at the underside of Minnesota and North Dakota.",
        "poster_url": "https://image.tmdb.org/t/p/w780/6mAHYNBPfhDxDr9xbz4mlr1UefM.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/vVFJxEsHBaBFacVFYJZGXgXVvT6.jpg",
        "trailer_youtube_id": "BxJKNhqI3VY",
        "available_on": ["hulu"], "tags": [],
    },
    {
        "id": "m_jackryan", "title": "Jack Ryan", "year": 2018, "rating": 7.5,
        "vote_count": 118000, "popularity": 65.0, "runtime": 60,
        "genres": ["Action", "Drama", "Thriller"], "type": "tv",
        "overview": "CIA analyst Jack Ryan is thrust into a dangerous field assignment for the first time as he uncovers a pattern in terrorist communication.",
        "poster_url": "https://image.tmdb.org/t/p/w780/B3kdkeNMsY3RNJLzMgPITxJEvo.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/6thddwRa5IfenNJLVBf5gETzpPO.jpg",
        "trailer_youtube_id": "9VWTDdHV6sU",
        "available_on": ["prime_video"], "tags": [],
    },
    {
        "id": "m_promisingyoungwoman", "title": "Promising Young Woman", "year": 2020, "rating": 7.5,
        "vote_count": 198000, "popularity": 78.0, "runtime": 113,
        "genres": ["Drama", "Thriller", "Crime"], "type": "movie",
        "overview": "Nothing in Cassie's life is what it appears to be — she's smart, talented and, by all appearances, a woman who has it all. Now, nothing will stop her quest for the ultimate revenge.",
        "poster_url": "https://image.tmdb.org/t/p/w780/5UkzNSOK561c2QRy2Zr4AkADzLT.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/sVSzS1aWuGFMVNVhVW1V6qvkEGc.jpg",
        "trailer_youtube_id": "tGaNMVMaOaM",
        "available_on": ["prime_video", "peacock"], "tags": [],
    },
    {
        "id": "m_nocountryforoldmen", "title": "No Country for Old Men", "year": 2007, "rating": 8.2,
        "vote_count": 325000, "popularity": 102.0, "runtime": 122,
        "genres": ["Crime", "Drama", "Thriller"], "type": "movie",
        "overview": "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.",
        "poster_url": "https://image.tmdb.org/t/p/w780/jK8FJNdmBxkBp3BXaEVGw0PUNhV.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/ya7bTCiSJ2lhgHR9F0z71HBjxlT.jpg",
        "trailer_youtube_id": "38A__WT3-o0",
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_tenet", "title": "Tenet", "year": 2020, "rating": 7.3,
        "vote_count": 248000, "popularity": 88.0, "runtime": 150,
        "genres": ["Sci-Fi", "Action", "Thriller"], "type": "movie",
        "overview": "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
        "poster_url": "https://image.tmdb.org/t/p/w780/k68nPLbIST6NP96JmTxmZijZcpB.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/wzJRB4MKi3yK138bpyqAoFciHas.jpg",
        "trailer_youtube_id": "LdOM0x0XDMo",
        "available_on": ["hbo_max"], "tags": [],
    },
    {
        "id": "m_aquietplace", "title": "A Quiet Place", "year": 2018, "rating": 7.5,
        "vote_count": 352000, "popularity": 112.0, "runtime": 90,
        "genres": ["Horror", "Drama", "Sci-Fi"], "type": "movie",
        "overview": "In a post-apocalyptic world where most humans have been killed by blind but noise-sensitive creatures, a family struggles to survive.",
        "poster_url": "https://image.tmdb.org/t/p/w780/nAU74GmpUk7t5iklEp3bufnDKPo.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/mSteqBzAGMYkJuZseqBRXEEiQmO.jpg",
        "trailer_youtube_id": "WR7cc5t7tv8",
        "available_on": ["prime_video", "peacock"], "tags": [],
    },
    {
        "id": "m_revenant", "title": "The Revenant", "year": 2015, "rating": 8.0,
        "vote_count": 330000, "popularity": 108.0, "runtime": 156,
        "genres": ["Drama", "Adventure", "Action"], "type": "movie",
        "overview": "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.",
        "poster_url": "https://image.tmdb.org/t/p/w780/ji3ecJphATlVgV8pVZHCEh2iSrZ.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/2DmsvJFepSNGhKXrHAl7dHIJVbA.jpg",
        "trailer_youtube_id": "LoebZZ8K5N0",
        "available_on": ["hulu", "prime_video"], "tags": [],
    },
    {
        "id": "m_joker2019", "title": "Joker", "year": 2019, "rating": 8.4,
        "vote_count": 440000, "popularity": 145.0, "runtime": 122,
        "genres": ["Crime", "Drama", "Thriller"], "type": "movie",
        "overview": "During the 1980s, a failed stand-up comedian is driven insane and becomes a murderous psychopath. A cautionary tale that explores the violent repercussions of society's ignorance.",
        "poster_url": "https://image.tmdb.org/t/p/w780/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/f5F4cRhQdUbyVbB5lTNC1bKCsrC.jpg",
        "trailer_youtube_id": "zAGVQLHvwOY",
        "available_on": ["hbo_max", "netflix"], "tags": [],
    },

    # ── Documentary seed content ─────────────────────────────────────────────
    # 18 curated entries with verified TMDB IDs covering: pure Documentary,
    # Documentary+Crime, Documentary+History, Documentary+Music, and docu-series.
    # These ensure Documentary is always in the catalog regardless of TMDB import state.

    # Pure Documentary (TV)
    {
        "id": "m_thelastdance", "title": "The Last Dance", "year": 2020, "rating": 8.3,
        "vote_count": 1467, "popularity": 5.4, "runtime": 50,
        "genres": ["Documentary"], "type": "tv",
        "overview": "Follows the 1997-98 Chicago Bulls dynasty with unprecedented access, centred on Michael Jordan's sixth and final championship run.",
        "poster_url": "https://image.tmdb.org/t/p/w780/oVf4xGGbDtwVHiKn8uTuSriY7PH.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/kY0h95L73t7a6ev6Rv0aHSCtN7y.jpg",
        "trailer_youtube_id": None,
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_ourplanet", "title": "Our Planet", "year": 2019, "rating": 8.5,
        "vote_count": 446, "popularity": 4.3, "runtime": 50,
        "genres": ["Documentary"], "type": "tv",
        "overview": "Experience our planet's natural beauty and witness the urgent stories of the challenges facing nature today — from the frozen arctic to tropical jungles.",
        "poster_url": "https://image.tmdb.org/t/p/w780/wRSnArnQBmeUYb5GWDU595bGsBr.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/p8EUX6MPSNLxVwqO3fCYTi896Ro.jpg",
        "trailer_youtube_id": None,
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_abstract", "title": "Abstract: The Art of Design", "year": 2017, "rating": 7.7,
        "vote_count": 77, "popularity": 1.3, "runtime": 45,
        "genres": ["Documentary"], "type": "tv",
        "overview": "Step inside the minds of the most innovative designers in the world and see how design shapes every aspect of life.",
        "poster_url": "https://image.tmdb.org/t/p/w780/mBpWUNGlB66cP6ght7NyT3jXmWN.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/q3sPqDh9zBMmj4RH0fZp9RM1Bwj.jpg",
        "trailer_youtube_id": None,
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_socialdilemma", "title": "The Social Dilemma", "year": 2020, "rating": 7.5,
        "vote_count": 1775, "popularity": 3.1, "runtime": 94,
        "genres": ["Documentary", "Drama"], "type": "movie",
        "overview": "Tech experts sound the alarm on the dangerous human impact of social networking, revealing how its design is meant to manipulate and exploit its users.",
        "poster_url": "https://image.tmdb.org/t/p/w780/jcaM6V2tCtu6iMHDsGLBUbaYgYp.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/iYqoT9VBGdGTuLl3cjfbG7ZXDkP.jpg",
        "trailer_youtube_id": None,
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_icarus2017", "title": "Icarus", "year": 2017, "rating": 7.6,
        "vote_count": 820, "popularity": 0.9, "runtime": 121,
        "genres": ["Documentary"], "type": "movie",
        "overview": "A filmmaker stumbles upon a vast state-sponsored doping scandal while trying an experiment on himself. Winner of the Academy Award for Best Documentary.",
        "poster_url": "https://image.tmdb.org/t/p/w780/x5azMi1KvZWbBbfjmGqpHNGqjH.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/ambKXAJYrDPJK9wBJlIVVWbQbar.jpg",
        "trailer_youtube_id": None,
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_blackfish", "title": "Blackfish", "year": 2013, "rating": 7.8,
        "vote_count": 1184, "popularity": 2.2, "runtime": 83,
        "genres": ["Documentary"], "type": "movie",
        "overview": "A documentary following the controversial captivity of killer whales and its impact on the animals and their handlers at SeaWorld.",
        "poster_url": "https://image.tmdb.org/t/p/w780/kCk4mDFE96Mn1AYfEcbxkIiw7ND.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/tCW0uGWwfZzRkupNFdI0yUo4A0w.jpg",
        "trailer_youtube_id": None,
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_freesolo", "title": "Free Solo", "year": 2018, "rating": 7.9,
        "vote_count": 1506, "popularity": 2.3, "runtime": 100,
        "genres": ["Documentary", "Adventure"], "type": "movie",
        "overview": "Follow Alex Honnold as he attempts to become the first person to ever free solo climb Yosemite's El Capitan — a 3,000-foot granite wall with no ropes.",
        "poster_url": "https://image.tmdb.org/t/p/w780/v4QfYZMACODlWul9doN9RxE99ag.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/z2uuQasY4gQJ8VDAFki746JWeQJ.jpg",
        "trailer_youtube_id": None,
        "available_on": ["prime_video", "netflix"], "tags": [],
    },

    # Documentary + Crime
    {
        "id": "m_makingamurderer", "title": "Making a Murderer", "year": 2015, "rating": 7.9,
        "vote_count": 559, "popularity": 1.0, "runtime": 55,
        "genres": ["Documentary", "Crime"], "type": "tv",
        "overview": "Filmed over ten years, this series follows Steven Avery — a Wisconsin man who served 18 years for a crime he didn't commit and later became a suspect in a new murder.",
        "poster_url": "https://image.tmdb.org/t/p/w780/sy2nV3rCcJQaRK5M0NWvvTU7CBx.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/i0bVPXHdvLQzE1Ld8dDwbCj1kOW.jpg",
        "trailer_youtube_id": None,
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_tigerking", "title": "Tiger King", "year": 2020, "rating": 6.9,
        "vote_count": 565, "popularity": 2.5, "runtime": 45,
        "genres": ["Documentary", "Crime"], "type": "tv",
        "overview": "A zoo owner spirals out of control amid a cast of eccentric characters, each more outrageous than the last in this wild true crime documentary.",
        "poster_url": "https://image.tmdb.org/t/p/w780/dXQCEjVth8P8L47XIsoRt0oL8Gw.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/8GGD7djS6oqTWcKwJb3uT833xeA.jpg",
        "trailer_youtube_id": None,
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_thekeepers", "title": "The Keepers", "year": 2017, "rating": 7.4,
        "vote_count": 195, "popularity": 1.0, "runtime": 55,
        "genres": ["Documentary", "Crime", "Mystery"], "type": "tv",
        "overview": "This gripping documentary series investigates the unsolved murder of a nun, and the shocking secrets that have been kept hidden for decades.",
        "poster_url": "https://image.tmdb.org/t/p/w780/kgZE2Hx2zCGNJMPbOet9B7IcWbu.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/tXRpbIxcQeGxfs0opfm6XgXAyzX.jpg",
        "trailer_youtube_id": None,
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_wildwildcountry", "title": "Wild Wild Country", "year": 2018, "rating": 7.7,
        "vote_count": 296, "popularity": 1.5, "runtime": 70,
        "genres": ["Documentary", "Crime"], "type": "tv",
        "overview": "When a cult builds a utopian city in rural Oregon, the locals are outraged, leading to the first major bioterror attack in US history and a massive case of wire-tapping.",
        "poster_url": "https://image.tmdb.org/t/p/w780/kprB5Jj2LYQAYlqVQMEucT2vGt.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/sDuM3zw8OBqfciFVwR2r2loGDte.jpg",
        "trailer_youtube_id": None,
        "available_on": ["netflix"], "tags": [],
    },

    # Documentary + History
    {
        "id": "m_13th", "title": "13th", "year": 2016, "rating": 7.9,
        "vote_count": 789, "popularity": 1.8, "runtime": 100,
        "genres": ["Documentary", "History"], "type": "movie",
        "overview": "Ava DuVernay's examination of the US prison system and the 13th Amendment reveals how slavery has been reinvented in modern America.",
        "poster_url": "https://image.tmdb.org/t/p/w780/tcKNWD6IFPPsvkpvyZ548naz0is.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/hwn9CN2x5Qhm3laLRvZlXttL6LU.jpg",
        "trailer_youtube_id": None,
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_apollo11", "title": "Apollo 11", "year": 2019, "rating": 7.9,
        "vote_count": 700, "popularity": 1.7, "runtime": 93,
        "genres": ["Documentary", "History"], "type": "movie",
        "overview": "A stunning look at the Apollo 11 mission to land on the moon, constructed from newly discovered reels of 65mm footage and audio recordings.",
        "poster_url": "https://image.tmdb.org/t/p/w780/woLMRroHyoTGoXyxdEeBJEYBFtu.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/el4j0LHk56uH6ErE5FZu2x5UJx8.jpg",
        "trailer_youtube_id": None,
        "available_on": ["prime_video"], "tags": [],
    },

    # Documentary + Music
    {
        "id": "m_summerofsouldoc", "title": "Summer of Soul", "year": 2021, "rating": 7.6,
        "vote_count": 219, "popularity": 1.3, "runtime": 117,
        "genres": ["Documentary", "Music", "History"], "type": "movie",
        "overview": "Director Questlove unearths long-lost footage of the 1969 Harlem Cultural Festival — a historic concert series celebrating Black history, music and culture.",
        "poster_url": "https://image.tmdb.org/t/p/w780/8kNwhqUGvpzWJd60O1Qvb8G6psK.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/1LYWnmr5K3Hs3XEZ323bY0dBZsK.jpg",
        "trailer_youtube_id": None,
        "available_on": ["prime_video", "hulu"], "tags": [],
    },
    {
        "id": "m_missamericana", "title": "Miss Americana", "year": 2020, "rating": 7.8,
        "vote_count": 641, "popularity": 1.4, "runtime": 86,
        "genres": ["Documentary", "Music"], "type": "movie",
        "overview": "A raw and revealing look at Taylor Swift during a transformational period in her life as she finds her voice in the political landscape.",
        "poster_url": "https://image.tmdb.org/t/p/w780/z1HiEB1UEfdA5fPkngekjQ2vlCC.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/A7AjlQTR1UlaNSYwwPRQ5gQTHyf.jpg",
        "trailer_youtube_id": None,
        "available_on": ["netflix"], "tags": [],
    },
    {
        "id": "m_amywinehousedoc", "title": "Amy", "year": 2015, "rating": 7.6,
        "vote_count": 1313, "popularity": 1.9, "runtime": 128,
        "genres": ["Documentary", "Music"], "type": "movie",
        "overview": "The story of Amy Winehouse — her extraordinary talent and her troubled life — in her own words, featuring never-before-seen footage.",
        "poster_url": "https://image.tmdb.org/t/p/w780/qL0RepWSNUuZoeDXfyhqowVYhrn.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/8YiAnbmo8ARHNVt25Cp5fVt4rNd.jpg",
        "trailer_youtube_id": None,
        "available_on": ["prime_video"], "tags": [],
    },
    {
        "id": "m_20feetstardom", "title": "20 Feet from Stardom", "year": 2013, "rating": 7.2,
        "vote_count": 260, "popularity": 0.7, "runtime": 91,
        "genres": ["Documentary", "Music"], "type": "movie",
        "overview": "Backup singers who have spent their careers behind music's biggest stars finally step out of the shadows in this Academy Award-winning documentary.",
        "poster_url": "https://image.tmdb.org/t/p/w780/6iRxKxfE6SB586cQV3BH8NSMzoZ.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/wUop1B76njSptV0B0s8YUFRRG5I.jpg",
        "trailer_youtube_id": None,
        "available_on": ["prime_video"], "tags": [],
    },
    {
        "id": "m_defiantones", "title": "The Defiant Ones", "year": 2017, "rating": 7.8,
        "vote_count": 100, "popularity": 2.8, "runtime": 60,
        "genres": ["Documentary", "Music"], "type": "tv",
        "overview": "An intimate look at the unlikely partnership between music moguls Dr. Dre and Jimmy Iovine, and how they changed the music industry forever.",
        "poster_url": "https://image.tmdb.org/t/p/w780/38JFkjD3SZvbDKvgDEXPUXbK5d0.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/8K1GMQTRDXxLjMANVoZIfncb89l.jpg",
        "trailer_youtube_id": None,
        "available_on": ["hbo_max"], "tags": [],
    },
]
