"""Seed data: streaming services, genres, and movies/shows.

Movie posters and backdrops use TMDB-public CDN style image URLs (image.tmdb.org)
which serve real, well-known title artwork. These are public assets used widely.
"""

STREAMING_SERVICES = [
    {"id": "netflix",      "name": "Netflix",      "price_monthly": 15.49, "logo_color": "#E50914", "affiliate_url": "https://www.netflix.com/"},
    {"id": "disney_plus",  "name": "Disney+",      "price_monthly": 13.99, "logo_color": "#0E47A1", "affiliate_url": "https://www.disneyplus.com/"},
    {"id": "hbo_max",      "name": "Max",          "price_monthly": 15.99, "logo_color": "#002BE7", "affiliate_url": "https://www.max.com/"},
    {"id": "prime_video",  "name": "Prime Video",  "price_monthly":  8.99, "logo_color": "#00A8E1", "affiliate_url": "https://www.primevideo.com/"},
    {"id": "apple_tv",     "name": "Apple TV+",    "price_monthly":  9.99, "logo_color": "#A6A6A6", "affiliate_url": "https://tv.apple.com/"},
    {"id": "hulu",         "name": "Hulu",         "price_monthly":  7.99, "logo_color": "#1CE783", "affiliate_url": "https://www.hulu.com/"},
    {"id": "paramount",    "name": "Paramount+",   "price_monthly":  7.99, "logo_color": "#0064FF", "affiliate_url": "https://www.paramountplus.com/"},
    {"id": "peacock",      "name": "Peacock",      "price_monthly":  7.99, "logo_color": "#FA6400", "affiliate_url": "https://www.peacocktv.com/"},
]

GENRES = [
    "Action", "Adventure", "Animation", "Comedy", "Crime", "Documentary",
    "Drama", "Fantasy", "Horror", "Mystery", "Romance", "Sci-Fi",
    "Thriller", "Western",
]

# id, title, year, rating (TMDB-style 0-10), runtime (min), genres, overview,
# poster_url, backdrop_url, trailer_youtube_id, available_on
SEED_MOVIES = [
    {
        "id": "m_oppenheimer", "title": "Oppenheimer", "year": 2023, "rating": 8.4, "runtime": 180,
        "genres": ["Drama", "Thriller"], "type": "movie",
        "overview": "The story of J. Robert Oppenheimer's role in the development of the atomic bomb.",
        "poster_url": "https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
        "trailer_youtube_id": "uYPbbksJxIg",
        "available_on": ["peacock", "prime_video"],
    },
    {
        "id": "m_dune2", "title": "Dune: Part Two", "year": 2024, "rating": 8.3, "runtime": 166,
        "genres": ["Sci-Fi", "Adventure"], "type": "movie",
        "overview": "Paul Atreides unites with the Fremen to take revenge against the conspirators who destroyed his family.",
        "poster_url": "https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
        "trailer_youtube_id": "Way9Dexny3w",
        "available_on": ["hbo_max"],
    },
    {
        "id": "m_succession", "title": "Succession", "year": 2018, "rating": 8.9, "runtime": 60,
        "genres": ["Drama", "Comedy"], "type": "tv",
        "overview": "Follows the lives of the Roy family as they contemplate their future once their patriarch begins to step back from the media empire.",
        "poster_url": "https://image.tmdb.org/t/p/w780/7HW47XbkNQ5fiwQFYGWdw9gs144.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/AeKCJEcmpJzNGuhPhrmeLaaO0F4.jpg",
        "trailer_youtube_id": "OzYxJV_rmE8",
        "available_on": ["hbo_max"],
    },
    {
        "id": "m_severance", "title": "Severance", "year": 2022, "rating": 8.7, "runtime": 55,
        "genres": ["Sci-Fi", "Mystery", "Thriller"], "type": "tv",
        "overview": "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.",
        "poster_url": "https://image.tmdb.org/t/p/w780/lFf6LLrQjYldcZItzOkGmMMigP7.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/wnjjkqFVK9o4Cg5GVeXa5jK4Bvn.jpg",
        "trailer_youtube_id": "xEQP4VVuyrY",
        "available_on": ["apple_tv"],
    },
    {
        "id": "m_thebear", "title": "The Bear", "year": 2022, "rating": 8.5, "runtime": 30,
        "genres": ["Drama", "Comedy"], "type": "tv",
        "overview": "A young chef from the fine-dining world returns to Chicago to run his late brother's sandwich shop.",
        "poster_url": "https://image.tmdb.org/t/p/w780/zPyHo2rfnLIkXbkVdHFOXoZALDJ.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/yZNfO3LDDtAvKBpYTVRDSrPnclI.jpg",
        "trailer_youtube_id": "Ux1iX5RKfUE",
        "available_on": ["hulu", "disney_plus"],
    },
    {
        "id": "m_killersflowermoon", "title": "Killers of the Flower Moon", "year": 2023, "rating": 7.6, "runtime": 206,
        "genres": ["Crime", "Drama", "Western"], "type": "movie",
        "overview": "Members of the Osage tribe in the United States are murdered under mysterious circumstances in the 1920s.",
        "poster_url": "https://image.tmdb.org/t/p/w780/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/270RtIhkDqf1eyMUq3wkz3iMCAh.jpg",
        "trailer_youtube_id": "EP34Yoxs3FQ",
        "available_on": ["apple_tv", "prime_video"],
    },
    {
        "id": "m_strangerthings", "title": "Stranger Things", "year": 2016, "rating": 8.6, "runtime": 50,
        "genres": ["Sci-Fi", "Horror", "Drama"], "type": "tv",
        "overview": "When a young boy vanishes, a small town uncovers a mystery involving secret experiments and supernatural forces.",
        "poster_url": "https://image.tmdb.org/t/p/w780/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
        "trailer_youtube_id": "b9EkMc79ZSU",
        "available_on": ["netflix"],
    },
    {
        "id": "m_thecrown", "title": "The Crown", "year": 2016, "rating": 8.6, "runtime": 60,
        "genres": ["Drama"], "type": "tv",
        "overview": "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the 20th century.",
        "poster_url": "https://image.tmdb.org/t/p/w780/1M876KPjulVwppEpldhdc8V4o68.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/nGsv7uqfkSlTkW8WMnPVoEKyDrJ.jpg",
        "trailer_youtube_id": "JWtnJjn6ng0",
        "available_on": ["netflix"],
    },
    {
        "id": "m_andor", "title": "Andor", "year": 2022, "rating": 8.4, "runtime": 50,
        "genres": ["Sci-Fi", "Action", "Adventure"], "type": "tv",
        "overview": "Cassian Andor's journey to discover the difference he can make in the Star Wars galaxy on a mission of revenge.",
        "poster_url": "https://image.tmdb.org/t/p/w780/loFmBXAXTaPpeJYrJMnk4F8e2hG.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/cbFFQk5dmUHukyEYlCay82SDPDV.jpg",
        "trailer_youtube_id": "Vk6FmzPXZoQ",
        "available_on": ["disney_plus"],
    },
    {
        "id": "m_lastofus", "title": "The Last of Us", "year": 2023, "rating": 8.7, "runtime": 60,
        "genres": ["Drama", "Action", "Horror"], "type": "tv",
        "overview": "Twenty years after modern civilization has been destroyed, Joel must smuggle Ellie out of an oppressive quarantine zone.",
        "poster_url": "https://image.tmdb.org/t/p/w780/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
        "trailer_youtube_id": "uLtkt8BonwM",
        "available_on": ["hbo_max"],
    },
    {
        "id": "m_poorthings", "title": "Poor Things", "year": 2023, "rating": 7.9, "runtime": 141,
        "genres": ["Comedy", "Drama", "Sci-Fi"], "type": "movie",
        "overview": "The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant scientist Dr. Godwin Baxter.",
        "poster_url": "https://image.tmdb.org/t/p/w780/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
        "trailer_youtube_id": "RR6N5KYDdTk",
        "available_on": ["hulu", "disney_plus"],
    },
    {
        "id": "m_pastlives", "title": "Past Lives", "year": 2023, "rating": 7.9, "runtime": 105,
        "genres": ["Drama", "Romance"], "type": "movie",
        "overview": "Two childhood friends are reunited 20 years later to confront notions of love and destiny.",
        "poster_url": "https://image.tmdb.org/t/p/w780/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/n4GJFGzsc7NinI1VeGDXIcQjtU2.jpg",
        "trailer_youtube_id": "kA37rOOY3yU",
        "available_on": ["paramount", "prime_video"],
    },
    {
        "id": "m_tedlasso", "title": "Ted Lasso", "year": 2020, "rating": 8.6, "runtime": 30,
        "genres": ["Comedy", "Drama"], "type": "tv",
        "overview": "American football coach Ted Lasso heads to London to manage AFC Richmond, a struggling English Premier League soccer team.",
        "poster_url": "https://image.tmdb.org/t/p/w780/5fhZdwP1DVJ0FyVHvfO0XfLjsQk.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
        "trailer_youtube_id": "3u7EIiohs6U",
        "available_on": ["apple_tv"],
    },
    {
        "id": "m_barbie", "title": "Barbie", "year": 2023, "rating": 7.2, "runtime": 114,
        "genres": ["Comedy", "Adventure", "Fantasy"], "type": "movie",
        "overview": "Barbie suffers a crisis that leads her to question her world and her existence.",
        "poster_url": "https://image.tmdb.org/t/p/w780/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/nHf61UzkfFno5X1ofIhugCPus5n.jpg",
        "trailer_youtube_id": "pBk4NYhWNMM",
        "available_on": ["hbo_max"],
    },
    {
        "id": "m_breakingbad", "title": "Breaking Bad", "year": 2008, "rating": 8.9, "runtime": 49,
        "genres": ["Drama", "Crime", "Thriller"], "type": "tv",
        "overview": "A high school chemistry teacher diagnosed with terminal cancer turns to manufacturing meth to secure his family's future.",
        "poster_url": "https://image.tmdb.org/t/p/w780/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
        "trailer_youtube_id": "HhesaQXLuRY",
        "available_on": ["netflix"],
    },
    {
        "id": "m_themandalorian", "title": "The Mandalorian", "year": 2019, "rating": 8.4, "runtime": 40,
        "genres": ["Sci-Fi", "Action", "Adventure"], "type": "tv",
        "overview": "A lone gunfighter makes his way through the outer reaches of the galaxy, far from the authority of the New Republic.",
        "poster_url": "https://image.tmdb.org/t/p/w780/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/9ijMGlJKqcslswWUzTEwScm82Gs.jpg",
        "trailer_youtube_id": "aOC8E8z_ifw",
        "available_on": ["disney_plus"],
    },
    {
        "id": "m_johnwick4", "title": "John Wick: Chapter 4", "year": 2023, "rating": 7.7, "runtime": 169,
        "genres": ["Action", "Thriller", "Crime"], "type": "movie",
        "overview": "John Wick uncovers a path to defeating The High Table, but before he can earn his freedom, he must face off against a new enemy.",
        "poster_url": "https://image.tmdb.org/t/p/w780/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
        "trailer_youtube_id": "qEVUtrk8_B4",
        "available_on": ["peacock", "prime_video"],
    },
    {
        "id": "m_whitelotus", "title": "The White Lotus", "year": 2021, "rating": 7.9, "runtime": 60,
        "genres": ["Drama", "Comedy", "Mystery"], "type": "tv",
        "overview": "The exploits of various guests and employees at a tropical resort over the span of a week.",
        "poster_url": "https://image.tmdb.org/t/p/w780/gP7OBvAmuW0gWCiZv7aw0vBXgOh.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/bJP6bOfdIwskaW4PwCw9NPL62qY.jpg",
        "trailer_youtube_id": "TEGEcA3Ar50",
        "available_on": ["hbo_max"],
    },
    {
        "id": "m_spiderverse", "title": "Spider-Man: Across the Spider-Verse", "year": 2023, "rating": 8.4, "runtime": 140,
        "genres": ["Animation", "Action", "Adventure"], "type": "movie",
        "overview": "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
        "poster_url": "https://image.tmdb.org/t/p/w780/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/4HodYYKEIsGOdinkGi2Ucwxn3Vp.jpg",
        "trailer_youtube_id": "cqGjhVJWtEg",
        "available_on": ["netflix"],
    },
    {
        "id": "m_house_dragon", "title": "House of the Dragon", "year": 2022, "rating": 8.4, "runtime": 60,
        "genres": ["Drama", "Fantasy", "Action"], "type": "tv",
        "overview": "The Targaryen civil war, known as the Dance of the Dragons, set 200 years before the events of Game of Thrones.",
        "poster_url": "https://image.tmdb.org/t/p/w780/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
        "trailer_youtube_id": "DotnHcOpCB8",
        "available_on": ["hbo_max"],
    },
    {
        "id": "m_anatomyfall", "title": "Anatomy of a Fall", "year": 2023, "rating": 7.7, "runtime": 152,
        "genres": ["Drama", "Crime", "Mystery"], "type": "movie",
        "overview": "A woman is suspected of murder after her husband's death; their half-blind son faces a moral dilemma as the main witness.",
        "poster_url": "https://image.tmdb.org/t/p/w780/kQs6keheMwCxJxrzV83VUwFtHkB.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/27mpiyhqAN0Pz9hbf85t1EtvnvK.jpg",
        "trailer_youtube_id": "lE9VRCi4yXQ",
        "available_on": ["hulu", "prime_video"],
    },
    {
        "id": "m_friends", "title": "Friends", "year": 1994, "rating": 8.4, "runtime": 22,
        "genres": ["Comedy", "Romance"], "type": "tv",
        "overview": "Six young people navigate life and love in Manhattan in this iconic sitcom.",
        "poster_url": "https://image.tmdb.org/t/p/w780/f496cm9enuEsZkSPzCwnTESEK5s.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/l0qVZIpXtIo7km9u5Yqh0nKPOr5.jpg",
        "trailer_youtube_id": "cBR-XLLEVew",
        "available_on": ["hbo_max"],
    },
    {
        "id": "m_loki", "title": "Loki", "year": 2021, "rating": 8.2, "runtime": 50,
        "genres": ["Sci-Fi", "Fantasy", "Action"], "type": "tv",
        "overview": "The mercurial villain Loki resumes his role as the God of Mischief in a new series that takes place after the events of Avengers: Endgame.",
        "poster_url": "https://image.tmdb.org/t/p/w780/voHUmluYmKyleFkTu3lOXQG702u.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/g0rCwu0t4hL4nwAerFqSXlZdBrE.jpg",
        "trailer_youtube_id": "nW948Va-l10",
        "available_on": ["disney_plus"],
    },
    {
        "id": "m_tar", "title": "Tár", "year": 2022, "rating": 7.4, "runtime": 158,
        "genres": ["Drama"], "type": "movie",
        "overview": "Set in the international world of classical music, the film centers on Lydia Tár, a renowned conductor.",
        "poster_url": "https://image.tmdb.org/t/p/w780/n13UJrZNEY4u0PuvjAo5pjDe0OL.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/aDFiTqQMV5VyiQ3OOLGu9XAmfPv.jpg",
        "trailer_youtube_id": "aZkBaywpAEQ",
        "available_on": ["peacock"],
    },
]
