// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/discover-refresh/Current.tsx": () => import("../components/mockups/discover-refresh/Current.tsx"),
  "./components/mockups/discover-refresh/Refreshed.tsx": () => import("../components/mockups/discover-refresh/Refreshed.tsx")
};
